# Only apply +crt-static when building for Linux targets (not proc macros on the host)
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.amd64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
